nova:
  name: Nova框架示例项目
  sql:
    print: true
  font-backend: false
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/nova
    username: postgres
    password: postgres
  redis:
    host: localhost
    port: 6379
    password:

