nova:
  name: nova
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    clean-disabled: true
    locations: classpath:db/migration/{vendor}
  main:
    allow-circular-references: true
